version: "3.8"
services:
  fatcat_db:
    container_name: fatcat_db
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: fatcat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: locdam
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '4321:4321'
    networks:
      - postgres
  fatcat_api:
    container_name: fatcat_api
    image: promisebello/fatcattask
    build: 
      context: .
    restart: always
    ports:
      - "4002:4002"
    environment:
      DB_HOST: fatcat
      DB_USERNAME: postgres
      DB_PASSWORD: locdam
    depends_on:
      - fatcat_db
    networks:
      - postgres
volumes:
  pgdata: {}
networks:
  postgres:
    driver: bridge